### ISSUE TITLE
Methods Due 12/04 10:00pm

### ISSUE THREAD

**Issue by VenusMeow** [VenusMeow/CurrencySiri#1]
The main frame of the program is written and uploaded as CurrencySiri.java.
There are four methods to be written.
Everyone please pick one method from the four, reply to this issue with your chosen method, and try to write up the method before 10:00 pm tomorrow. 
Thanks!

**Comment by VenusMeow** [comment]
These are the four methods:

public static Double getInitialValue (String[] input) {
    // this recognizes the number in the user's input as the initial value
  }

  public static String getInitialCurr (String[] input){
    // this recognizes the initial currency in the user's input
  }

  public static String getFinalCurr (String[] input){
    // this recognizes the final currency in the user's input
  }

  public static Double getRate (String iCurr, String fCurr){
    // this gets the exchange rate between the two currency
    // it shall be used in the formula final value = initial value / rate
    // be careful of its order
}

**Comment by irishaohaohao** [comment]
I'll do this one
public static Double getInitialValue (String[] input) {
// this recognizes the number in the user's input as the initial value
}

**Comment by Gia1220** [comment]
I'll do the second one

**Comment by VenusMeow** [comment]
When you are writing up the code for the methods that reads in from the array of inputs, try imagine the user would input: "what is 100 USD in RMB?"

**Comment by Jessie201115** [comment]
Can I do the final currency part?

**Comment by VenusMeow** [comment]
okay I'll do the get rate part
